# this is an invoice

id = "001"
currency = "GBP"
currency_symbol = "Â£"
amount = "300"
issue_date = "2023-11-30"
due_date = "2023-12-30"
metric_title = "Time (hours)"

[from]
name = "alifeee"
address = "123 Fake Street, Sheffield, S8 4GF"
email = "alifeee@alifeee.co.uk"
bank = "alifeee 95-11-15 84958174"

[to]
name = "Garibaldi"
address = "123 Fake Street, Sheffield, S8 4GF"
email = "old@biscuits.co.uk"


[[items]]
title = "Biscuit Generation"
url = "https://www.github.com/alifeee/issues/4"
metric = "1.5"
charge = "150"

[[items]]
title = "Biscuit Testing"
metric = "1"
charge = "100"

[[items]]
title = "Biscuit Packaging"
url = "https://www.github.com/alifeee/issues/6"
metric = "0.5"
charge = "50"
